# Use this configuration if you have multiple (here: 3) ESPARGOS boards
# which are all connected to the same master sync output.

app:
  camera:
    device: "/dev/video4"
    format: null
    flip: False
  beamformer:
    type: "FFT"
    polarization_mode: "show"
  visualization:
    space: "camera"

generic:
  preamble_format: "lltf"
  kiosk_mode: False

pool:
  channel: 5
  rf_switch: 4

backlog:
  size: 20
  fields:
    lltf: True
    ht20: False
    ht40: False

combined-array:
  boards:
    ba1:
      host: 172.16.0.151
      cable:
        length: 0.0
        velocity_factor: 0.76
    ba2:
      host: 172.16.0.152
      cable:
        length: 0.0
        velocity_factor: 0.76
    ba3:
      host: 172.16.0.153
      cable:
        length: 0.0
        velocity_factor: 0.76

  array:
    - - "ba1.1.0"
      - "ba1.0.0"
      - "ba2.1.0"
      - "ba2.0.0"
      - "ba3.1.0"
      - "ba3.0.0"
    - - "ba1.1.1"
      - "ba1.0.1"
      - "ba2.1.1"
      - "ba2.0.1"
      - "ba3.1.1"
      - "ba3.0.1"
    - - "ba1.1.2"
      - "ba1.0.2"
      - "ba2.1.2"
      - "ba2.0.2"
      - "ba3.1.2"
      - "ba3.0.2"
    - - "ba1.1.3"
      - "ba1.0.3"
      - "ba2.1.3"
      - "ba2.0.3"
      - "ba3.1.3"
      - "ba3.0.3"
